# Generated by Django 5.1 on 2024-09-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
