# Generated by Django 5.1 on 2024-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0002_alter_login_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
