# Generated by Django 5.1 on 2024-11-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0005_servicefaq_delete_faqhomeservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('package_name', models.CharField(max_length=255)),
                ('package_image', models.CharField(max_length=255)),
                ('package_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_services', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
