# Generated by Django 5.1 on 2024-11-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0006_package_remove_review_user_photo_image_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyAppPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('package_name', models.CharField(max_length=255)),
                ('package_image', models.ImageField(upload_to='package_images/')),
                ('package_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_services', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
